issuer: http://127.0.0.1:5556/dex
storage:
  type: sqlite3
  config:
    file: ./examples/dex.db
web:
  http: 0.0.0.0:5556
  https: 0.0.0.0:5557
  tlsCert: ./pki/dex.pem
  tlsKey: ./pki/dex-key.pem

#frontend:
#  dir: ../web

connectors:
- type: ldap
  name: FW-LDAP
  id: ldap
  config:
    host: nycwinadvip.fwmrm.net:389

    # No TLS for this setup.
    insecureNoSSL: true

    # This would normally be a read-only user.
    bindDN: CN=readonly,DC=freewheelmedia,DC=net
    bindPW: FWadmin

    usernamePrompt: Email Address

    userSearch:
      baseDN: OU=User Accounts,DC=freewheelmedia,DC=net
      filter: "(sAMAccountName={0})"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: ou=Groups,DC=freewheelmedia,DC=net
      filter: "(objectClass=groupOfNames)"

      # A user is a member of a group when their DN matches
      # the value of a "member" attribute on the group entity.
      userAttr: DN
      groupAttr: member

      # The group name should be the "cn" value.
      nameAttr: cn

staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"